area_data=[
  { 
    "id": 1,
    "LocationType": "School",
    "Name": "SK Kampung Pusu",
    "State": "Selangor",
    "AreaClassification": "Rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 3,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 2.1,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.88,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 5.2,
    "CommunityPopulation": 180,
    "FacilityPurpose": "Night tuition lighting",
    "VerifiedBeneficiary": True
  },
  {
    "id": 2,
    "LocationType": "Clinic",
    "Name": "Klinik Desa Hulu Langat",
    "State": "Selangor",
    "AreaClassification": "Semi-rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 4,
    "CurrentElectricityStatus": "Blackout",
    "RealTimeDemand_kWh": 3.5,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.92,
    "GridAvailability": "Down",
    "DistanceFromDonor_km": 12.4,
    "CommunityPopulation": 70,
    "FacilityPurpose": "Vaccine fridge & medical equipment",
    "VerifiedBeneficiary": True
  },
  {
    "id": 3,
    "LocationType": "Mosque",
    "Name": "Masjid Al-Hidayah Bentong",
    "State": "Pahang",
    "AreaClassification": "Rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 2,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 1.2,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.63,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 8.6,
    "CommunityPopulation": 250,
    "FacilityPurpose": "Prayer hall cooling and lighting",
    "VerifiedBeneficiary": True
  },
  {
    "id": 4,
    "LocationType": "Household",
    "Name": "Kg Orang Asli Kemensah",
    "State": "Selangor",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 1,
    "NaturalDisasterRisk": 3,
    "CurrentElectricityStatus": "Blackout",
    "RealTimeDemand_kWh": 0.8,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.95,
    "GridAvailability": "Down",
    "DistanceFromDonor_km": 14.7,
    "CommunityPopulation": 42,
    "FacilityPurpose": "Basic lighting and refrigeration",
    "VerifiedBeneficiary": True
  },
  {
    "id": 5,
    "LocationType": "Shelter",
    "Name": "Rumah Perlindungan Taman Melati",
    "State": "Kuala Lumpur",
    "AreaClassification": "Urban",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 1,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 1.7,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.54,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 3.1,
    "CommunityPopulation": 60,
    "FacilityPurpose": "Shelter cooling and security lights",
    "VerifiedBeneficiary": True
  },
  {
    "id": 6,
    "LocationType": "School",
    "Name": "SMK Kuala Nerus",
    "State": "Terengganu",
    "AreaClassification": "Semi-rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 4,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 2.8,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.71,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 9.8,
    "CommunityPopulation": 340,
    "FacilityPurpose": "Computer lab & exam hall",
    "VerifiedBeneficiary": True
  },
  {
    "id": 7,
    "LocationType": "Clinic",
    "Name": "Klinik Desa Jerantut",
    "State": "Pahang",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 3,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 3.0,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.89,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 20.4,
    "CommunityPopulation": 50,
    "FacilityPurpose": "Medication refrigeration",
    "VerifiedBeneficiary": True
  },
  {
    "id": 8,
    "LocationType": "Household",
    "Name": "PPR Lembah Subang Block C",
    "State": "Selangor",
    "AreaClassification": "Urban poor",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 1,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 1.1,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.52,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 6.0,
    "CommunityPopulation": 300,
    "FacilityPurpose": "Home lighting",
    "VerifiedBeneficiary": True
  },
  {
    "id": 9,
    "LocationType": "School",
    "Name": "SK Bagan Datuk",
    "State": "Perak",
    "AreaClassification": "Rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 4,
    "NaturalDisasterRisk": 2,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 1.9,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.39,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 18.2,
    "CommunityPopulation": 200,
    "FacilityPurpose": "Classroom fans and projectors",
    "VerifiedBeneficiary": True
  },
  {
    "id": 10,
    "LocationType": "Mosque",
    "Name": "Surau Al-Muttaqin, Gua Musang",
    "State": "Kelantan",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 4,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 1.6,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.84,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 23.5,
    "CommunityPopulation": 110,
    "FacilityPurpose": "Prayer hall lighting",
    "VerifiedBeneficiary": True
  },
  {
    "id": 11,
    "LocationType": "Clinic",
    "Name": "Klinik Desa Padang Terap",
    "State": "Kedah",
    "AreaClassification": "Rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 2,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 2.6,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.81,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 15.1,
    "CommunityPopulation": 65,
    "FacilityPurpose": "Cold chain vaccines",
    "VerifiedBeneficiary": True
  },
  {
    "id": 12,
    "LocationType": "Household",
    "Name": "Kg Kuala Kubu Bharu",
    "State": "Selangor",
    "AreaClassification": "Semi-rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 2,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 0.7,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.41,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 10.9,
    "CommunityPopulation": 95,
    "FacilityPurpose": "Home necessities",
    "VerifiedBeneficiary": True
  },
  {
    "id": 13,
    "LocationType": "School",
    "Name": "SK Long Bedian",
    "State": "Sarawak",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 1,
    "NaturalDisasterRisk": 3,
    "CurrentElectricityStatus": "Blackout",
    "RealTimeDemand_kWh": 3.4,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.97,
    "GridAvailability": "Down",
    "DistanceFromDonor_km": 32.7,
    "CommunityPopulation": 140,
    "FacilityPurpose": "School lighting & water pump",
    "VerifiedBeneficiary": True
  },
  {
    "id": 14,
    "LocationType": "Shelter",
    "Name": "Rumah Transit Wanita Sabah",
    "State": "Sabah",
    "AreaClassification": "Urban",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 2,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 2.0,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.66,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 4.4,
    "CommunityPopulation": 55,
    "FacilityPurpose": "Security lights & cooling",
    "VerifiedBeneficiary": True
  },
  {
    "id": 15,
    "LocationType": "Mosque",
    "Name": "Masjid Jamek Batu Arang",
    "State": "Selangor",
    "AreaClassification": "Semi-rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 4,
    "NaturalDisasterRisk": 1,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 1.0,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.28,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 7.3,
    "CommunityPopulation": 140,
    "FacilityPurpose": "Lights & audio",
    "VerifiedBeneficiary": True
  },
  {
    "id": 16,
    "LocationType": "Household",
    "Name": "Kg Telupid",
    "State": "Sabah",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 1,
    "NaturalDisasterRisk": 4,
    "CurrentElectricityStatus": "Blackout",
    "RealTimeDemand_kWh": 1.5,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.93,
    "GridAvailability": "Down",
    "DistanceFromDonor_km": 28.5,
    "CommunityPopulation": 90,
    "FacilityPurpose": "Basic power needs",
    "VerifiedBeneficiary": True
  },
  {
    "id": 17,
    "LocationType": "School",
    "Name": "SJKC Ladang Sungai Siput",
    "State": "Perak",
    "AreaClassification": "Rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 1,
    "CurrentElectricityStatus": "Stable",
    "RealTimeDemand_kWh": 1.3,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.35,
    "GridAvailability": "Full",
    "DistanceFromDonor_km": 12.8,
    "CommunityPopulation": 160,
    "FacilityPurpose": "Classroom usage",
    "VerifiedBeneficiary": True
  },
  {
    "id": 18,
    "LocationType": "Clinic",
    "Name": "Klinik Desa Kalabakan",
    "State": "Sabah",
    "AreaClassification": "Deep rural",
    "EconomyLevel": "Low",
    "EnergyStabilityScore": 2,
    "NaturalDisasterRisk": 4,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 2.9,
    "PeakHourNeed": True,
    "BeneficiaryPriorityScore": 0.87,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 40.2,
    "CommunityPopulation": 40,
    "FacilityPurpose": "Medical equipment & cold storage",
    "VerifiedBeneficiary": True
  },
  {
    "id": 19,
    "LocationType": "Mosque",
    "Name": "Surau Al-Qamar, Tasik Chini",
    "State": "Pahang",
    "AreaClassification": "Rural",
    "EconomyLevel": "Middle",
    "EnergyStabilityScore": 3,
    "NaturalDisasterRisk": 3,
    "CurrentElectricityStatus": "Unstable",
    "RealTimeDemand_kWh": 1.4,
    "PeakHourNeed": False,
    "BeneficiaryPriorityScore": 0.59,
    "GridAvailability": "Limited",
    "DistanceFromDonor_km": 21.1,
    "CommunityPopulation": 100,
    "FacilityPurpose": "Fans & lighting",
    "VerifiedBeneficiary": True
  }
]
